apiVersion: egress.cilium-egress-operator.io/v1alpha1
kind: EgressGateway
metadata:
  labels:
    app.kubernetes.io/name: cilium-egress-operator
    app.kubernetes.io/managed-by: kustomize
  name: egressgateway-sample
spec:
  # TODO(user): Add fields here
